### ISSUE TITLE
Bug: react-native-webview version

### ISSUE THREAD

**Issue by JordiParraCrespo** [Transak/react-native-sdk#11]
I installed the SDK with the version of: `"react-native-webview": "^12.1.0"` and it breaks on IOS.
Downgrading the version to:  `"react-native-webview": "11.23.1"` fix the issue.

**Comment by SamuhDigital** [comment]
Hi, I can make changes to the package.json file if you assign me this issue....

**Comment by Sachin24704** [comment]
Hi , can I create a pr to fix this issue ?

**Comment by debajitr** [comment]
Hi, tested this, it works fine with v13. I guess we can avoid downgrading.
